knpu_oauth2_client:
    clients:
        github:
            # must be "github" - it activates that type!
            type: github
            # add and configure client_id and client_secret in parameters.yml
            client_id: '%env(GITHUB_USERNAME)%'
            client_secret: '%env(GITHUB_SECRET)%'
            # a route name you'll create
            redirect_route: connect_github_check
            redirect_params: {}

            # whether to check OAuth2 "state": defaults to true
            # use_state: true